# Generated by Django 3.1.5 on 2021-01-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=64)),
                ('destination', models.TextField()),
                ('creation_date', models.DateField()),
                ('last_updated', models.DateTimeField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
