# Generated by Django 3.1.5 on 2021-01-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210123_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='destination',
            new_name='description',
        ),
    ]
