# Generated by Django 3.1.5 on 2021-01-23 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210123_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('creation_date', models.DateField(null=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TextType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('creation_date', models.DateField(null=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField()),
                ('text_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.texttype')),
            ],
        ),
    ]
