# Generated by Django 3.1.5 on 2021-01-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20210123_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='text',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='track',
            name='last_updated',
        ),
    ]
